FROM protobuff_cocoapi:1.0
WORKDIR /cv
COPY /src /cv/tfod
#RUN ["cd assets; && tar -xvf *.tar.gz"]
#in assets
RUN apt-get update &&\
    apt-get install ffmpeg libsm6 libxext6  -y &&\
    cd /cv/cocoapi/cocoapi/PythonAPI &&\
    cp -r pycocotools /cv/tfod/models/research/ &&\
    cd /cv/tfod/models/research &&\
    protoc object_detection/protos/*.proto --python_out=. &&\
    cp object_detection/packages/tf2/setup.py . &&\
    python -m pip install --use-feature=2020-resolver . &&\
    python object_detection/builders/model_builder_tf2_test.py &&\
    cp /cv/tfod/models/research/object_detection/exporter_main_v2.py /cv/tfod/workspace/training_demo/  

